.MODEL SMALL
.STACK 100H
.DATA

.CODE
	INICIO:
		MOV AX, @DATA
		MOV DS, AX
		
		PUSH AX
		PUSH BX	
		PUSH CX
		PUSH DX
		MOV AH, 06H ; DESPLAZAR LINEAS DE TEXTO HACIA ARRIBA
		MOV AL,10; NUMERO DE LINEAS A DESPLAZAR
		MOV BH, 62h ; FONDO BLANCO CON PRIMER PLANO AZUL
		
		MOv CH, 04;LINEA DONDE COMIENZA LA VENTANA DE TEXTO
		MOV DH, 20 ;LINEA DONDE ACABA VENTANADE TEXTO;
		
		MOV CL, 05 ; COLUMNA DONDE EMPIEZA VENTANA DE TEXTO
		MOV DL, 75 ;COLUMNA DONDE ACABA VENTANA DE TEXTO
		INT 10h
		
		POP DX
		POP CX 
		POP BX
		POP AX
		
		
		Mov ax,4c00h 
		int 21h 
		
	end INICIO