.MODEL SMALL
.STACK 100H
.DATA

.CODE
	INICIO:
		MOV AX, @DATA
		MOV DS, AX
		
		PUSH AX
		PUSH BX	
		PUSH CX
		PUSH DX
		MOV AH, 06H ; DESPLAZAR LINEAS DE TEXTO HACIA ARRIBA
		MOV AL,00h ; NUMERO DE LINEAS A DESPLAZAR
		MOV BH, 71h ; FONDO BLANCO CON PRIMER PLANO AZUL
		MOv CH, 04h;LINEA DONDE COMIENZA LA VENTANA DE TEXTO
		MOV CL, 05H ; COLUMNA DONDE EMPIEZA VENTANA DE TEXTO
		MOV DH, 6h ;LINEA DONDE ACABA VENTANADE TEXTO;;;;;;;;;;;;;;;;;;;;;;
		MOV DL, 37h ;COLUMNA DONDE ACABA VENTANA DE TEXTO
		INT 10h
		POP DX
		POP CX 
		POP BX
		POP AX
		
		
		Mov ax,4c00h 
		int 21h 
		
	end INICIO